backport a Rivet fix to CMS_2013_I1223519.cc
The AliGenerator bundle fails to be compiled in its daily builds due to an ambiguity in one of the 335 CMS plugin analyses.
Rivet/analyses/pluginCMS/CMS_2013_I1223519.cc in 2.7.2

pluginCMS/CMS_2013_I1223519.cc:156:54: error: reference to 'Et' is ambiguous
       vector<double> jetets; transform(jets, jetets, Et);
...

The issue has in fact been spotted a few months ago by the rivet authors and fix there for later version.
("Et" -> "Kin::Et") + ("biset" -> "std::bitset")

See official Rivet commits : 
https://gitlab.com/hepcedar/rivet/commit/ced494d4016dde5dcd24567a276942fa0f64c446
https://gitlab.com/hepcedar/rivet/commit/0d5f91a4c8e66f5c6cbd7d231c73a46be9c7109a